--- 
title: "Analytical Paleobiology"
author: "Peter D Smits"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: psmits/paleo_book
twitter-handle: PeterDSmits
description: "An informal course on analytical paleobiology"
---

# Preface {-}

This book is a series of tutorials on data analysis with examples drawn from paleobiology, macroevolution, and macroecology. Each chapter of this book can act as a 2-hour tutorial, with each lesson building on the previous ones. 

I emphasize Bayesian data analysis approaches throughout this text. Parameter inference is done using the [`brms`](https://github.com/paul-buerkner/brms) package which is a flexible tool for implementing [Stan-based](https://mc-stan.org/) models in R. 

This book uses the [`tidyverse`](https://www.tidyverse.org/) collection of R packages with a particular emphasis on `dplyr`, `ggplot2`, and `purrr`. Other `tidyverse` packages are used as necessary (e.g. `modelr`). Management and processing of posterior estimates, as well as some some aspects of visualization, is done using the [`tidybayes`](http://mjskay.github.io/tidybayes/) package. The [`pacman`](https://github.com/trinker/pacman) package is used throughout to ensure that all packages are both installed and loaded into namespace. The [`here`](https://github.com/r-lib/here) package is used to ensure safe file paths. I attempt to stick to the [`tidyverse` style guide](https://style.tidyverse.org/) as much as possible.

A lot of material in this book is derived from material and examples presented in 
[**Statistical Rethinking** by Richard McElreath](https://xcelab.net/rm/statistical-rethinking/), 
[**Bayesian Data Analysis 3** by Gelman et al.](http://www.stat.columbia.edu/~gelman/book/), and 
[**Data Analysis Using Regression and Multilevel/Hierarchical Models** by Gelman and Hill](https://www.cambridge.org/core/books/data-analysis-using-regression-and-multilevelhierarchical-models/32A29531C7FD730C3A68951A17C9D983). 

Additionally, some of the code used in this book is derived from [this rewriting](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse) of **Statistical Rethinking**.
